### ISSUE TITLE
Variable overwritten when "include" multiple files

### ISSUE THREAD

**Issue by PinkyJie** [pugjs/jade#2211]
Here is a simple demonstration:
```jade
// base.jade
block vars

div(class= cls)
  p test
```
```jade
// a.jade
extends base
block vars
  - var cls = "aaa"
  - var newVar = "bbb"
```
```jade
// b.jade
extends base
block vars
  - console.log(newVar)
```
```jade
// c.jade
include a
include b
```

Then I compiled `c.jade` using jade@1.11.0, the result is 
```html
<div class="aaa">
  <p>test</p>
</div>
<div class="aaa">
  <p>test</p>
</div>
```
And the console prints out the text `bbb`, which is the value  of `newVar`.

Two questions:
- Why the second `div` uses the same `cls` variable as the first `div`? I assume it should be empty.
- Why the new variable defined in `a.jade` can be accessed from `b.jade`?

How to handle this kind of variable overwritten? Is there some concept in jade like "Scoped Variable"?

**Comment by PinkyJie** [comment]
I also found an interesting thing, if I give the 2 variables a default value in `base.jade` and change the `block xxx` to `append xxx`, I can get the expected result.
```jade
// base.jade
block vars
  - var cls = ''
  - var newVar = ''
div(class= cls)
  p test
```
```jade
// a.jade
extends base
append vars
  - var cls = "aaa"
  - var newVar = "bbb"
```
```jade
// b.jade
extends base
append vars
  - console.log(newVar)
```
The compiled `c.jade` will be:
```html
<div class="aaa">
  <p>test</p>
</div>
<div>
  <p>test</p>
</div>
```
And this time no `bbb` printed in console.

However the problem is our template is so complicated, it contains many mixins and blocks, I can't set all variables might be used to empty in `base.jade`.

**Comment by tomlagier** [comment]
As far as I can tell, there is no concept of a scoped variable in Jade. Jade interprets all of your Javascript in the same scope - so if you declare a variable in one place and redeclare it somewhere else, you are bound to get errors.

For your latest example, if you think about what you've done, you've basically said in a.jade to declare two variables which, because they are replacing an existing block, sets them for the first time. 

Then in b, you are appending console.log to the base template's block, which sets the variables to an empty string. So if you were to visualize what your entire template looks like as it's being compiled, it would be:

````
//including a.jade

//base.jade's var block
- var cls = ''
- var newVar = ''

//append a.jade's var block
- var cls = 'aaa'
- var newVar =  'bbb'

//base.jade content
div(class= cls)
  p test

//including b.jade

//base.jade's var block
- var cls = ''
- var newVar = ''

//append b.jade's var block
- console.log(newVar)

//base.jade content
div(class= cls)
  p test
````

**Comment by TimothyGu** [comment]
Exactly. One way to think about the Jade `include` is comparing it to the C `#include` directive. (In reality it's a lot more complex than that, but it's a good analogy w/o getting into Jade internals.)

**Comment by PinkyJie** [comment]
@tomlagier @TimothyGu Thanks for explanation.
