### ISSUE TITLE
header tags fail to nest

### ISSUE THREAD

**Issue by jangajack** [pugjs/jade#2216]
I was going to nest a header tag inside a paragraph, but the resulting HTML was not nested. I did a quick search but found no reference to this being a function so I'm making this quick report. I will add to it as soon as possible. 

JADE markup
```
.content
   p: span: h1 What's up?
   p #[h2 What about this?]
   p: h5 Or this?
```

HTML result
```
<div class="content">
  <p><span></span></p>
  <h1>What's up?</h1>
  <p></p>
   <h2>What about this?</h2>
   <p></p>
   <h5>Or this?</h5>
 </div>
```

**Comment by TimothyGu** [comment]
Did you copy this HTML result from Devtools? This code is semantically wrong (since a block level tag doesn't belong in a inline tag, even though HTML5 relaxed that requirement IIRC) and your browser may try to correct that error. This corrected tree would be what shows up in the Devtools.

A quick check by copying this text into http://jade-lang.com/ shows that the HTML is generated properly, even though the tags are marked with red denoting the tag type violation.

**Comment by ForbesLindesay** [comment]
As @TimothyGu explained, Jade is generating the HTML you asked for, but when the browser parses it, it doesn't allow it as that HTML is invalid.

**Comment by jangajack** [comment]
Got it. Yes it was out of DevTools, and I appreciate the heads up about the compiling feature of the  [http://jade-lang.com/](http://jade-lang.com/) site, which confirmed Jade is compiling it correctly. Thank you.
